### ISSUE TITLE
error with NavigationsView

### ISSUE THREAD

**Issue by seransaca** [jrvansuita/CheckNewAppVersionAvailable#2]
When I introduce the library dependency and run the app(without code.java) the app crash with this message:

android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class android.support.design.widget.NavigationView

**Comment by jrvansuita** [comment]
Hi @seransaca, I just successful tested my library with an app that contains a NavigationView implementation. I experienced no issues with that. Can you paste here some source code. Make sure you are using  compile 'com.android.support:design:25.0.0' as dependency.

**Comment by seransaca** [comment]
At the moment I compile with version 22-23 with what I can not have 'com.android.support:design:25.0.0' dependency.
When I compile with version 25 I tell you if I could use your library.
Thanks for the information

**Comment by jrvansuita** [comment]
Ok @seransaca
